spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  redis:
    host: localhost
    port: 6379
    password: <ваш_пароль>
    timeout: 5000

  jpa:
    hibernate:
      ddl-auto: create-drop
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  liquibase:
    enabled: true  # Включаем  Liquibase для управления миграциями
    change-log: classpath:/db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

server:
  port: 8080
